// Generated by npm run build. Includes MIT-licensed pi-ai helpers; see THIRD_PARTY_NOTICES.

// src/index.ts
import { createProvider } from "@earendil-works/pi-ai";

// src/auth.ts
import { randomUUID } from "node:crypto";

// node_modules/@earendil-works/pi-ai/dist/utils/abort.js
function abortReason(signal) {
  if (signal.reason !== void 0)
    return signal.reason;
  const error = new Error("The operation was aborted");
  error.name = "AbortError";
  return error;
}
function raceWithAbortSignal(operation, signal) {
  if (signal.aborted) {
    void operation.catch(() => {
    });
    return Promise.reject(abortReason(signal));
  }
  return new Promise((resolve, reject) => {
    let settled = false;
    const cleanup = () => signal.removeEventListener("abort", onAbort);
    const onAbort = () => {
      if (settled)
        return;
      settled = true;
      cleanup();
      reject(abortReason(signal));
    };
    signal.addEventListener("abort", onAbort, { once: true });
    void operation.then((value) => {
      if (settled)
        return;
      settled = true;
      cleanup();
      resolve(value);
    }, (error) => {
      if (settled)
        return;
      settled = true;
      cleanup();
      reject(error);
    });
    if (signal.aborted)
      onAbort();
  });
}

// src/http.ts
import { EnvHttpProxyAgent, fetch } from "undici";
function object(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}
function environment(options) {
  return { ...process.env, ...options?.env };
}
function headers(...sources) {
  const result = new Headers();
  for (const source of sources) {
    for (const [name, value] of Object.entries(source ?? {})) {
      if (value === null) result.delete(name);
      else result.set(name, value);
    }
  }
  return result;
}
var queue = Promise.resolve();
function serial(signal, work) {
  const pending = queue.then(() => {
    signal.throwIfAborted();
    return work();
  });
  queue = pending.then(
    () => {
    },
    () => {
    }
  );
  return raceWithAbortSignal(pending, signal);
}
var GigaChatHttpError = class extends Error {
  constructor(status, body) {
    super(
      `GigaChat HTTP ${status}${status === 413 ? " context_length_exceeded" : ""}: ${body}`
    );
    this.status = status;
  }
  status;
};
async function request(url, init, options, consume, observe) {
  const env = environment(options);
  const timeout = options.timeoutMs ?? Number(env.GIGACHAT_TIMEOUT ?? 300) * 1e3;
  if (!Number.isFinite(timeout) || timeout <= 0)
    throw new Error("GigaChat timeout must be positive");
  const signal = AbortSignal.any([
    ...options.signal ? [options.signal] : [],
    AbortSignal.timeout(Math.ceil(timeout))
  ]);
  signal.throwIfAborted();
  const proxy = (name) => options.env?.[name.toLowerCase()] ?? options.env?.[name] ?? env[name.toLowerCase()] ?? env[name] ?? "";
  const dispatcher = new EnvHttpProxyAgent({
    httpProxy: proxy("HTTP_PROXY"),
    httpsProxy: proxy("HTTPS_PROXY"),
    noProxy: proxy("NO_PROXY")
  });
  let response;
  try {
    const send = options.fetch ?? fetch;
    response = await send(url, { ...init, signal, dispatcher });
    await observe?.(response);
    if (!response.ok)
      throw new GigaChatHttpError(response.status, await response.text());
    return await consume(response);
  } catch (error) {
    if (signal.aborted) throw signal.reason;
    if (error instanceof Error && error.message === "fetch failed" && error.cause instanceof Error)
      throw new Error(`GigaChat connection failed: ${error.cause.message}`, {
        cause: error
      });
    throw error;
  } finally {
    if (response?.body && !response.body.locked)
      await response.body.cancel().catch(() => {
      });
    await dispatcher.close();
  }
}

// src/models.ts
var GIGACHAT_API = "gigachat-extension-api";
var GIGACHAT_DEFAULT_BASE_URL = "https://api.giga.chat/v1";
var GIGACHAT_MODELS = [
  ["GigaChat-2", "GigaChat 2 Lite"],
  ["GigaChat-2-Pro", "GigaChat 2 Pro"],
  ["GigaChat-2-Max", "GigaChat 2 Max"],
  ["GigaChat-3-Ultra", "GigaChat 3 Ultra"]
].map(([id, name]) => ({
  id,
  name,
  api: GIGACHAT_API,
  provider: "gigachat",
  baseUrl: GIGACHAT_DEFAULT_BASE_URL,
  reasoning: false,
  input: ["text"],
  // Unknown USD prices; tariffs vary by account. Zero is not a free-tier claim.
  cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
  contextWindow: 128e3,
  maxTokens: 8192
}));

// src/auth.ts
var scopes = ["GIGACHAT_API_PERS", "GIGACHAT_API_B2B", "GIGACHAT_API_CORP"];
var authUrl = "https://ngw.devices.sberbank.ru:9443/api/v2/oauth";
function baseUrl(value = GIGACHAT_DEFAULT_BASE_URL) {
  const url = new URL(value);
  if (!["https:", "http:"].includes(url.protocol))
    throw new Error("GigaChat base URL must use http(s)");
  return url.href.replace(/\/+$/, "");
}
async function exchange(stored, signal, env = {}) {
  const config = environment({ env });
  const passwordAuth = stored.authMode === "basic";
  const scope = stored.scope || scopes[0];
  if (!scopes.includes(scope))
    throw new Error(`Invalid GigaChat scope: use ${scopes.join(", ")}`);
  const authorization = passwordAuth ? Buffer.from(`${stored.user}:${stored.password}`).toString("base64") : (stored.authorizationKey || stored.refresh).replace(/^Basic\s+/i, "").trim();
  if (!authorization || passwordAuth && (!stored.user || !stored.password))
    throw new Error("GigaChat login credentials are missing");
  const data = await request(
    passwordAuth ? `${baseUrl(stored.baseUrl)}/token` : config.GIGACHAT_AUTH_URL || authUrl,
    {
      method: "POST",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
        Accept: "application/json",
        Authorization: `Basic ${authorization}`,
        RqUID: randomUUID(),
        "User-Agent": "pi-gigachat"
      },
      body: passwordAuth ? "" : new URLSearchParams({ scope }).toString()
    },
    { signal, env },
    (response) => response.json()
  );
  if (!object(data)) throw new Error("Invalid GigaChat token response");
  const access = data.access_token ?? data.tok;
  const expiry = Number(data.expires_at ?? data.exp);
  if (typeof access !== "string" || !access || !Number.isFinite(expiry) || expiry <= 0)
    throw new Error(
      "Invalid GigaChat token response: missing access_token or expires_at"
    );
  return {
    ...stored,
    type: "oauth",
    access,
    expires: (expiry > 1e12 ? expiry : expiry * 1e3) - 6e4
  };
}
var cached;
async function configuration(ctx, credential) {
  const env = { ...credential?.env };
  for (const name of [
    "GIGACHAT_ACCESS_TOKEN",
    "GIGACHAT_CREDENTIALS",
    "GIGACHAT_USER",
    "GIGACHAT_PASSWORD",
    "GIGACHAT_SCOPE",
    "GIGACHAT_BASE_URL",
    "GIGACHAT_AUTH_URL",
    "GIGACHAT_TIMEOUT",
    "GIGACHAT_STREAM",
    "GIGACHAT_EXTRA_BODY",
    "GIGACHAT_SYSTEM_PROMPT",
    "HTTP_PROXY",
    "HTTPS_PROXY",
    "NO_PROXY",
    "http_proxy",
    "https_proxy",
    "no_proxy"
  ]) {
    const value = env[name] ?? await ctx.env(name);
    if (value !== void 0) env[name] = value;
  }
  const access = credential?.key || env.GIGACHAT_ACCESS_TOKEN;
  const configured = Boolean(
    access || env.GIGACHAT_CREDENTIALS || env.GIGACHAT_USER && env.GIGACHAT_PASSWORD
  );
  return { env, access, configured };
}
var gigachatAuth = {
  apiKey: {
    name: "GigaChat access token",
    async login({ prompt, signal }) {
      const key = (await prompt({ type: "secret", message: "GigaChat access token" })).trim().replace(/^Bearer\s+/i, "");
      signal.throwIfAborted();
      if (!key) throw new Error("GigaChat access token is required");
      return { type: "api_key", key };
    },
    async check({ ctx, credential, signal }) {
      signal.throwIfAborted();
      return (await configuration(ctx, credential)).configured ? { type: "api_key", source: "GigaChat credentials" } : void 0;
    },
    async resolve({ ctx, credential, signal }) {
      const { env, access, configured } = await configuration(ctx, credential);
      if (!configured) return void 0;
      let apiKey = access?.trim().replace(/^Bearer\s+/i, "");
      if (!apiKey) {
        apiKey = await serial(signal, async () => {
          const key = JSON.stringify([
            env.GIGACHAT_CREDENTIALS,
            env.GIGACHAT_USER,
            env.GIGACHAT_PASSWORD,
            env.GIGACHAT_SCOPE,
            env.GIGACHAT_BASE_URL,
            env.GIGACHAT_AUTH_URL
          ]);
          if (cached?.key !== key || cached.credential.expires <= Date.now()) {
            const next = await exchange(
              {
                type: "oauth",
                access: "",
                expires: 0,
                refresh: env.GIGACHAT_CREDENTIALS ?? "",
                authMode: env.GIGACHAT_CREDENTIALS ? "token" : "basic",
                scope: env.GIGACHAT_SCOPE,
                baseUrl: env.GIGACHAT_BASE_URL,
                user: env.GIGACHAT_USER,
                password: env.GIGACHAT_PASSWORD
              },
              signal,
              env
            );
            cached = { key, credential: next };
          }
          return cached.credential.access;
        });
      }
      return {
        auth: {
          apiKey,
          ...env.GIGACHAT_BASE_URL ? { baseUrl: baseUrl(env.GIGACHAT_BASE_URL) } : {}
        },
        // Do not relabel ambient proxy variables as request-scoped overrides.
        env: {
          ...Object.fromEntries(
            Object.entries(env).filter(
              ([name]) => name.startsWith("GIGACHAT_")
            )
          ),
          ...credential?.env
        }
      };
    }
  },
  oauth: {
    name: "GigaChat",
    loginLabel: "Authorization key or username/password (automatic token renewal)",
    async login({ prompt, signal, notify }) {
      const authMode = await prompt({
        type: "select",
        message: "GigaChat authentication",
        options: [
          { id: "token", label: "Authorization key" },
          { id: "basic", label: "Username and password" }
        ]
      });
      const url = baseUrl(
        (await prompt({
          type: "text",
          message: "GigaChat base URL",
          placeholder: GIGACHAT_DEFAULT_BASE_URL
        })).trim() || process.env.GIGACHAT_BASE_URL || GIGACHAT_DEFAULT_BASE_URL
      );
      const scope = await prompt({
        type: "select",
        message: "GigaChat scope",
        options: scopes.map((id) => ({ id, label: id }))
      });
      const stored = {
        type: "oauth",
        access: "",
        refresh: "",
        expires: 0,
        authMode,
        scope,
        baseUrl: url
      };
      if (authMode === "basic") {
        stored.user = (await prompt({ type: "text", message: "GigaChat username" })).trim();
        stored.password = await prompt({
          type: "secret",
          message: "GigaChat password"
        });
      } else {
        stored.refresh = (await prompt({
          type: "secret",
          message: "GigaChat authorization key (not access token)"
        })).trim().replace(/^Basic\s+/i, "");
      }
      signal.throwIfAborted();
      notify({
        type: "progress",
        message: "Requesting GigaChat access token\u2026"
      });
      return exchange(stored, signal);
    },
    refresh: (credential, signal) => exchange(credential, signal),
    async toAuth(credential) {
      return {
        apiKey: credential.access,
        ...credential.baseUrl ? { baseUrl: baseUrl(credential.baseUrl) } : {}
      };
    }
  }
};

// src/stream.ts
import { randomUUID as randomUUID2 } from "node:crypto";
import {
  calculateCost,
  createAssistantMessageEventStream,
  parseStreamingJson
} from "@earendil-works/pi-ai";
import { createParser } from "eventsource-parser";

// node_modules/@earendil-works/pi-ai/dist/api/transform-messages.js
var NON_VISION_USER_IMAGE_PLACEHOLDER = "(image omitted: model does not support images)";
var NON_VISION_TOOL_IMAGE_PLACEHOLDER = "(tool image omitted: model does not support images)";
function replaceImagesWithPlaceholder(content, placeholder) {
  const result = [];
  let previousWasPlaceholder = false;
  for (const block of content) {
    if (block.type === "image") {
      if (!previousWasPlaceholder) {
        result.push({ type: "text", text: placeholder });
      }
      previousWasPlaceholder = true;
      continue;
    }
    result.push(block);
    previousWasPlaceholder = block.text === placeholder;
  }
  return result;
}
function downgradeUnsupportedImages(messages, model) {
  if (model.input.includes("image")) {
    return messages;
  }
  return messages.map((msg) => {
    if (msg.role === "user" && Array.isArray(msg.content)) {
      return {
        ...msg,
        content: replaceImagesWithPlaceholder(msg.content, NON_VISION_USER_IMAGE_PLACEHOLDER)
      };
    }
    if (msg.role === "toolResult") {
      return {
        ...msg,
        content: replaceImagesWithPlaceholder(msg.content, NON_VISION_TOOL_IMAGE_PLACEHOLDER)
      };
    }
    return msg;
  });
}
function transformMessages(messages, model, normalizeToolCallId) {
  const toolCallIdMap = /* @__PURE__ */ new Map();
  const normalizedMessages = messages.map((msg) => msg.content == null ? { ...msg, content: [] } : msg);
  const imageAwareMessages = downgradeUnsupportedImages(normalizedMessages, model);
  const transformed = imageAwareMessages.map((msg) => {
    if (msg.role === "user") {
      return msg;
    }
    if (msg.role === "toolResult") {
      const normalizedId = toolCallIdMap.get(msg.toolCallId);
      if (normalizedId && normalizedId !== msg.toolCallId) {
        return { ...msg, toolCallId: normalizedId };
      }
      return msg;
    }
    if (msg.role === "assistant") {
      const assistantMsg = msg;
      const isSameModel = assistantMsg.provider === model.provider && assistantMsg.api === model.api && assistantMsg.model === model.id;
      const transformedContent = assistantMsg.content.flatMap((block) => {
        if (block.type === "thinking") {
          if (block.redacted) {
            return isSameModel ? block : [];
          }
          if (isSameModel && block.thinkingSignature)
            return block;
          if (!block.thinking || block.thinking.trim() === "")
            return [];
          if (isSameModel)
            return block;
          return {
            type: "text",
            text: block.thinking
          };
        }
        if (block.type === "text") {
          if (isSameModel)
            return block;
          return {
            type: "text",
            text: block.text
          };
        }
        if (block.type === "toolCall") {
          const toolCall = block;
          let normalizedToolCall = toolCall;
          if (!isSameModel && toolCall.thoughtSignature) {
            normalizedToolCall = { ...toolCall };
            delete normalizedToolCall.thoughtSignature;
          }
          if (!isSameModel && normalizeToolCallId) {
            const normalizedId = normalizeToolCallId(toolCall.id, model, assistantMsg);
            if (normalizedId !== toolCall.id) {
              toolCallIdMap.set(toolCall.id, normalizedId);
              normalizedToolCall = { ...normalizedToolCall, id: normalizedId };
            }
          }
          return normalizedToolCall;
        }
        return block;
      });
      return {
        ...assistantMsg,
        content: transformedContent
      };
    }
    return msg;
  });
  const result = [];
  let pendingToolCalls = [];
  let existingToolResultIds = /* @__PURE__ */ new Set();
  const insertSyntheticToolResults = () => {
    if (pendingToolCalls.length > 0) {
      for (const tc of pendingToolCalls) {
        if (!existingToolResultIds.has(tc.id)) {
          result.push({
            role: "toolResult",
            toolCallId: tc.id,
            toolName: tc.name,
            content: [{ type: "text", text: "No result provided" }],
            isError: true,
            timestamp: Date.now()
          });
        }
      }
      pendingToolCalls = [];
      existingToolResultIds = /* @__PURE__ */ new Set();
    }
  };
  for (let i = 0; i < transformed.length; i++) {
    const msg = transformed[i];
    if (msg.role === "assistant") {
      insertSyntheticToolResults();
      const assistantMsg = msg;
      if (assistantMsg.stopReason === "error" || assistantMsg.stopReason === "aborted") {
        continue;
      }
      const toolCalls = assistantMsg.content.filter((b) => b.type === "toolCall");
      if (toolCalls.length > 0) {
        pendingToolCalls = toolCalls;
        existingToolResultIds = /* @__PURE__ */ new Set();
      }
      result.push(msg);
    } else if (msg.role === "toolResult") {
      existingToolResultIds.add(msg.toolCallId);
      result.push(msg);
    } else if (msg.role === "user") {
      insertSyntheticToolResults();
      result.push(msg);
    } else {
      result.push(msg);
    }
  }
  insertSyntheticToolResults();
  return result;
}

// src/messages.ts
var STATE_SIGNATURE_PREFIX = "gigachat:functions_state_id:";
function convertMessages(model, context, additionalSystemPrompt) {
  const messages = [];
  const transformedMessages = transformMessages(context.messages, model);
  const systemPrompt = [context.systemPrompt, additionalSystemPrompt?.trim()].filter(Boolean).join("\n\n");
  if (systemPrompt) {
    messages.push({
      role: "system",
      content: sanitizeSurrogates(systemPrompt)
    });
  }
  for (let i = 0; i < transformedMessages.length; i++) {
    const message = transformedMessages[i];
    if (message.role === "user") {
      if (typeof message.content === "string") {
        messages.push({
          role: "user",
          content: sanitizeSurrogates(message.content)
        });
      } else {
        const text = message.content.filter((item) => item.type === "text").map((item) => sanitizeSurrogates(item.text)).join("\n");
        if (text.length > 0) {
          messages.push({ role: "user", content: text });
        }
      }
      continue;
    }
    if (message.role === "assistant") {
      const text = message.content.filter((item) => item.type === "text").map((item) => sanitizeSurrogates(item.text)).join("");
      const toolCalls = message.content.filter(
        (item) => item.type === "toolCall"
      );
      if (toolCalls.length > 0) {
        const results = /* @__PURE__ */ new Map();
        while (transformedMessages[i + 1]?.role === "toolResult") {
          const result = transformedMessages[++i];
          results.set(result.toolCallId, result);
        }
        for (const [callIndex, call] of toolCalls.entries()) {
          messages.push({
            role: "assistant",
            content: callIndex === 0 ? text : "",
            function_call: { name: call.name, arguments: call.arguments },
            functions_state_id: readStateSignature(call.thoughtSignature)
          });
          const result = results.get(call.id);
          results.delete(call.id);
          messages.push({
            role: "function",
            name: call.name,
            content: JSON.stringify({
              result: result ? toolResultText(result) : "No result provided",
              ...result?.isError || !result ? { isError: true } : {}
            })
          });
        }
        for (const result of results.values()) {
          messages.push(unmatchedToolResult(result));
        }
      } else {
        const signature = message.content.find(
          (block) => block.type === "text" && readStateSignature(block.textSignature)
        );
        messages.push({
          role: "assistant",
          content: text,
          functions_state_id: signature?.type === "text" ? readStateSignature(signature.textSignature) : void 0
        });
      }
      continue;
    }
    const toolMessage = message;
    messages.push(unmatchedToolResult(toolMessage));
  }
  return messages;
}
function unmatchedToolResult(message) {
  return {
    role: "user",
    content: `Tool result (${message.toolName}):
${toolResultText(message)}`
  };
}
function readStateSignature(signature) {
  return signature?.startsWith(STATE_SIGNATURE_PREFIX) ? signature.slice(STATE_SIGNATURE_PREFIX.length) : void 0;
}
function toolResultText(message) {
  const text = message.content.filter((item) => item.type === "text").map((item) => sanitizeSurrogates(item.text)).join("\n") || "(no content)";
  return message.isError ? `Error: ${text}` : text;
}
function convertFunctions(tools) {
  return tools.map(({ name, description, parameters }) => ({
    name,
    description,
    parameters: JSON.parse(JSON.stringify(parameters))
  }));
}
function sanitizeSurrogates(text) {
  return text.toWellFormed();
}

// src/stream.ts
function payload(model, context, options) {
  const env = environment(options);
  const mode = env.GIGACHAT_STREAM ?? "false";
  if (mode !== "true" && mode !== "false")
    throw new Error("GIGACHAT_STREAM must be true or false");
  let extra;
  try {
    extra = JSON.parse(env.GIGACHAT_EXTRA_BODY || "{}");
  } catch {
    throw new Error("GIGACHAT_EXTRA_BODY must be a JSON object");
  }
  if (!object(extra))
    throw new Error("GIGACHAT_EXTRA_BODY must be a JSON object");
  const maxTokens = options.maxTokens ?? model.maxTokens;
  if (!Number.isFinite(maxTokens) || maxTokens < 1)
    throw new Error("GigaChat maxTokens must be positive");
  return {
    model: model.id,
    messages: convertMessages(model, context, env.GIGACHAT_SYSTEM_PROMPT),
    max_tokens: Math.floor(Math.min(maxTokens, model.maxTokens)),
    function_call: options.toolChoice ?? options.functionCall ?? (context.tools?.length ? "auto" : "none"),
    ...context.tools?.length ? { functions: convertFunctions(context.tools) } : {},
    temperature: options.temperature,
    top_p: options.topP,
    response_format: options.responseFormat,
    profanity_check: options.profanityCheck,
    repetition_penalty: options.repetitionPenalty,
    ...model.samplingParams,
    ...options.samplingParams,
    ...extra,
    ...options.extraBody,
    stream: options.stream ?? mode === "true"
  };
}
function streamSimpleGigaChat(model, context, options = {}) {
  if (!options.apiKey)
    throw new Error(
      "GigaChat access token is required; use gigachatProvider with createModels() or /login gigachat"
    );
  const stream = createAssistantMessageEventStream();
  const output = {
    role: "assistant",
    content: [],
    api: model.api,
    provider: model.provider,
    model: model.id,
    stopReason: "pending",
    timestamp: Date.now(),
    usage: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
      totalTokens: 0,
      cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, total: 0 }
    }
  };
  const signal = options.signal ?? new AbortController().signal;
  (async () => {
    try {
      let body = payload(model, context, options);
      const streaming = body.stream;
      const modified = await options.onPayload?.(body, model);
      if (modified !== void 0) {
        if (!object(modified))
          throw new Error("GigaChat onPayload must return a JSON object");
        body = modified;
      }
      body.stream = streaming;
      stream.push({ type: "start", partial: output });
      await serial(
        signal,
        () => request(
          // Native auth already applied the saved or ambient endpoint to the
          // model. Only an explicit request override may replace it here.
          `${baseUrl(options.env?.GIGACHAT_BASE_URL || model.baseUrl)}/chat/completions`,
          {
            method: "POST",
            body: JSON.stringify(body),
            headers: headers(
              {
                "Content-Type": "application/json",
                Accept: streaming ? "text/event-stream" : "application/json",
                Authorization: `Bearer ${options.apiKey}`,
                "User-Agent": "pi-gigachat",
                "Cache-Control": "no-store",
                ...options.sessionId && options.cacheRetention !== "none" ? { "X-Session-ID": options.sessionId } : {}
              },
              model.headers,
              options.headers
            )
          },
          options,
          async (response) => {
            const consume = completionConsumer(output, stream, model);
            if (streaming)
              await readSSE(response, (chunk) => consume.add(chunk, true));
            else {
              if (!response.headers.get("content-type")?.includes("application/json"))
                throw new Error("Expected a GigaChat JSON response");
              consume.add(await response.json(), false);
            }
            consume.finish();
          },
          (response) => options.onResponse?.(
            {
              status: response.status,
              headers: Object.fromEntries(response.headers)
            },
            model
          )
        )
      );
      signal.throwIfAborted();
      if (output.stopReason !== "stop" && output.stopReason !== "length" && output.stopReason !== "toolUse")
        throw new Error(
          `GigaChat finished with reason: ${output.rawStopReason ?? output.stopReason}`
        );
      stream.push({ type: "done", reason: output.stopReason, message: output });
    } catch (error) {
      output.stopReason = signal.aborted ? "aborted" : "error";
      output.errorMessage = error instanceof Error ? error.message : String(error);
      stream.push({ type: "error", reason: output.stopReason, error: output });
    } finally {
      stream.end();
    }
  })();
  return stream;
}
function completionConsumer(output, stream, model) {
  let text;
  let tool;
  let argumentsJson = "";
  let signature;
  let textClosed = false;
  const closeText = () => {
    if (text && !textClosed) {
      stream.push({
        type: "text_end",
        contentIndex: output.content.indexOf(text),
        content: text.text,
        partial: output
      });
      textClosed = true;
    }
  };
  const addText = (delta) => {
    if (textClosed) throw new Error("GigaChat sent text after a function call");
    if (!text) {
      text = { type: "text", text: "" };
      output.content.push(text);
      stream.push({
        type: "text_start",
        contentIndex: output.content.indexOf(text),
        partial: output
      });
    }
    text.text += delta;
    stream.push({
      type: "text_delta",
      contentIndex: output.content.indexOf(text),
      delta,
      partial: output
    });
  };
  return {
    add(chunk, streaming) {
      if (!object(chunk) || !Array.isArray(chunk.choices))
        throw new Error("Invalid GigaChat completion: missing choices");
      if (object(chunk.usage)) {
        const usage = output.usage;
        usage.input = Number(chunk.usage.prompt_tokens ?? 0);
        usage.output = Number(chunk.usage.completion_tokens ?? 0);
        usage.cacheRead = Number(chunk.usage.precached_prompt_tokens ?? 0);
        usage.totalTokens = usage.input + usage.cacheRead + usage.output;
        calculateCost(model, usage);
      }
      if (streaming && chunk.choices.length === 0 && object(chunk.usage))
        return;
      const choice = chunk.choices[0];
      const message = object(choice) ? choice[streaming ? "delta" : "message"] : void 0;
      if (!object(message))
        throw new Error(
          "Invalid GigaChat completion: missing message or delta"
        );
      if (message.role === "function_in_progress") return;
      if (message.content != null && typeof message.content !== "string")
        throw new Error("Invalid GigaChat content");
      if (typeof message.functions_state_id === "string")
        signature = STATE_SIGNATURE_PREFIX + message.functions_state_id;
      if (message.content) addText(message.content);
      if (message.function_call != null) {
        const call = message.function_call;
        if (!object(call)) throw new Error("Invalid GigaChat function_call");
        if (!tool) {
          closeText();
          tool = {
            type: "toolCall",
            id: `gigachat_${randomUUID2()}`,
            name: "",
            arguments: {}
          };
          output.content.push(tool);
          stream.push({
            type: "toolcall_start",
            contentIndex: output.content.indexOf(tool),
            partial: output
          });
        }
        if (typeof call.name === "string" && tool.name !== call.name)
          tool.name += call.name;
        if (call.arguments !== void 0) {
          if (typeof call.arguments !== "string" && !object(call.arguments))
            throw new Error("Invalid GigaChat function arguments");
          const delta = typeof call.arguments === "string" ? call.arguments : JSON.stringify(call.arguments);
          argumentsJson = typeof call.arguments === "string" ? argumentsJson + delta : delta;
          tool.arguments = parseStreamingJson(argumentsJson);
          stream.push({
            type: "toolcall_delta",
            contentIndex: output.content.indexOf(tool),
            delta,
            partial: output
          });
        }
      }
      if (choice.finish_reason != null && choice.finish_reason !== "") {
        output.rawStopReason = choice.finish_reason;
        switch (choice.finish_reason) {
          case "stop":
            output.stopReason = "stop";
            break;
          case "length":
            output.stopReason = "length";
            break;
          case "function_call":
            output.stopReason = "toolUse";
            break;
          default:
            throw new Error(`GigaChat finish_reason: ${choice.finish_reason}`);
        }
      }
    },
    finish() {
      if (output.stopReason === "pending")
        throw new Error("Incomplete GigaChat response: missing finish_reason");
      if (output.stopReason === "toolUse" && !tool)
        throw new Error("Invalid GigaChat completion: missing function_call");
      if (signature && !tool && !text) addText("");
      if (text && signature) text.textSignature = signature;
      closeText();
      if (tool) {
        const args = JSON.parse(argumentsJson || "{}");
        if (!tool.name || !object(args))
          throw new Error("Invalid GigaChat function_call name or arguments");
        tool.arguments = args;
        if (signature) tool.thoughtSignature = signature;
        stream.push({
          type: "toolcall_end",
          contentIndex: output.content.indexOf(tool),
          toolCall: tool,
          partial: output
        });
      }
    }
  };
}
async function readSSE(response, consume) {
  if (!response.headers.get("content-type")?.includes("text/event-stream") || !response.body)
    throw new Error("Expected a GigaChat SSE response");
  let done = false;
  const parser = createParser({
    onEvent(event) {
      if (event.data === "[DONE]") done = true;
      else if (!done) consume(JSON.parse(event.data));
    }
  });
  const decoder = new TextDecoder();
  const reader = response.body.getReader();
  try {
    while (!done) {
      const next = await reader.read();
      if (next.done) break;
      parser.feed(decoder.decode(next.value, { stream: true }));
    }
    parser.feed(decoder.decode());
    if (!done)
      throw new Error("Incomplete GigaChat SSE response: missing [DONE]");
  } finally {
    await reader.cancel().catch(() => {
    });
    reader.releaseLock();
  }
}

// src/index.ts
var gigachatProvider = createProvider({
  id: "gigachat",
  name: "GigaChat",
  auth: gigachatAuth,
  models: GIGACHAT_MODELS,
  api: { stream: streamSimpleGigaChat, streamSimple: streamSimpleGigaChat }
});
function index_default(pi) {
  pi.registerProvider(gigachatProvider);
}
export {
  index_default as default,
  gigachatProvider,
  streamSimpleGigaChat
};
