import { build } from 'esbuild';

// Pi aliases the public pi-ai entrypoint, but not its internal helper paths.
// Bundle those helpers from the pinned development version; retain host APIs.
await build({
  entryPoints: ['src/index.ts'],
  outfile: 'extension.js',
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  external: ['undici', 'eventsource-parser'],
  plugins: [{
    name: 'pi-host-api',
    setup(build) {
      build.onResolve({ filter: /^@earendil-works\/pi-ai$/ }, args => ({ path: args.path, external: true }));
    },
  }],
  banner: { js: '// Generated by npm run build. Includes MIT-licensed pi-ai helpers; see THIRD_PARTY_NOTICES.' },
});
